### ISSUE TITLE
td1coef

### ISSUE THREAD

**Issue by duncanelliott** [NinaGon/SpecParser#1]
When I use a spec file such as the following in the spec parser is returns a 6 variable trading day regressor rather than the 1 coefficient working day regressor. Is it possible to modify?

series{
  title = "nsa_ts"
file = "data.dta"
  format = "datevalue"
  period = 12
}

transform{
  function = none
  print = aictransform
}

x11{
  trendma = 7
  seasonalma = s3x5
  save = (d10 d11 d12 d13 d16 e18)
}

regression{
  variables = td1coef
}

arima{
  model = (1 0 0)(0 1 1)
}

**Comment by NinaGon** [comment]
Hi Duncan,
I fixed it. The new release is here: https://github.com/bbkrd/SpecParser/releases/tag/2.0.22
